# global configurations

Institution = "University of Yaounde I"
Faculty = "Faculty of Science"
Department = "Department of Computer Science"
Level = "Master 1"
ProjectName = "DREAMHOUSE237"
Supervisor = "Mr. Kemtho paul"