server.port=8086

# Eureka
eureka.client.service-url.defaultZone=http://ec2-16-171-42-48.eu-north-1.compute.amazonaws.com:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# RabbitMQ
spring.rabbitmq.host=ec2-16-171-42-48.eu-north-1.compute.amazonaws.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}