server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://ec2-16-171-142-15.eu-north-1.compute.amazonaws.com:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=ec2-16-171-142-15.eu-north-1.compute.amazonaws.com
eureka.instance.instance-id=proxy-service:8080

# Gateway discovery
spring.cloud.gateway.discovery.locator.enabled=false

# Load balancer
spring.cloud.loadbalancer.strategy=round-robin

# Actuator
management.endpoints.web.exposure.include=*

# ============================
# ROUTES MANUELLES
# ============================

# ---- AUTHENTIFICATION SERVICE ----
spring.cloud.gateway.routes[0].id=authentification
spring.cloud.gateway.routes[0].uri=lb://AUTHENTIFICATION
spring.cloud.gateway.routes[0].predicates[0]=Path=/AUTHENTIFICATION/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/AUTHENTIFICATION/(?<segment>.*), /api/auth/${segment}

# ---- PROPERTY SERVICE ----
spring.cloud.gateway.routes[1].id=property-service
spring.cloud.gateway.routes[1].uri=lb://property
spring.cloud.gateway.routes[1].predicates[0]=Path=/PROPERTY/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/PROPERTY/(?<segment>.*), /${segment}

# ---- DREAMHOUSE SERVICE ----
spring.cloud.gateway.routes[2].id=dreamhouse
spring.cloud.gateway.routes[2].uri=lb://dreamhouse
spring.cloud.gateway.routes[2].predicates[0]=Path=/DREAMHOUSE/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/DREAMHOUSE/(?<segment>.*), /${segment}

# ---- USER SERVICE ----
spring.cloud.gateway.routes[3].id=user-service
spring.cloud.gateway.routes[3].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/USER-SERVICE/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/USER-SERVICE/(?<segment>.*), /${segment}

# ---- COMMENTARY SERVICE ----
spring.cloud.gateway.routes[4].id=commentary-service
spring.cloud.gateway.routes[4].uri=lb://COMMENTARY-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/COMMENTARY-SERVICE/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/COMMENTARY-SERVICE/(?<segment>.*), /${segment}

# ---- PUBLICATION SERVICE ----
spring.cloud.gateway.routes[5].id=publication-service
spring.cloud.gateway.routes[5].uri=lb://publication-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/PUBLICATION-SERVICE/**
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/PUBLICATION-SERVICE/(?<segment>.*), /${segment}

# ---- PAYMENT SERVICE ----
spring.cloud.gateway.routes[6].id=payment-service
spring.cloud.gateway.routes[6].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/PAYMENT-SERVICE/**
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/PAYMENT-SERVICE/(?<segment>.*), /${segment}

# ---- IDENTITY SERVICE ----
spring.cloud.gateway.routes[7].id=identity-service
spring.cloud.gateway.routes[7].uri=lb://IDENTITY-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/IDENTITY-SERVICE/**
spring.cloud.gateway.routes[7].filters[0]=RewritePath=/IDENTITY-SERVICE/(?<segment>.*), /${segment}

# LOGGING
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.cors=DEBUG
logging.level.com.dreamhouse237=DEBUG

# CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[0]=https://dreamhouse237.onrender.com
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins[1]=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
#spring.cloud.gateway.default-filters[0]=DeduplicateResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_LAST